window.DRESS_UP_ITEMS = {
  tops: [
    {
      id: "top_1",
      label: "니트 탑",
      color: "#888888",
      description: "포근한 니트 소재의 상의",
      price: 54000,
    },
    {
      id: "top_2",
      label: "소닉 셔츠",
      color: "#888888",
      description: "캐릭터 프린트가 있는 셔츠",
      price: 140000,
    },
    {
      id: "top_3",
      label: "아톰 티셔츠",
      color: "#888888",
      description: "클래식한 캐릭터 티셔츠",
      price: 15000,
    },
    {
      id: "top_4",
      label: "블록 나시",
      color: "#888888",
      description: "블록 패턴의 나시 탑",
      price: 50000,
    },
    {
      id: "top_5",
      label: "반팔 바람막이",
      color: "#888888",
      description: "가볍고 활동하기 좋은 바람막이",
      price: 180000,
    },
    {
      id: "top_6",
      label: "체커보드 민소매 셔츠",
      color: "#888888",
      description: "체크 패턴의 민소매 셔츠",
      price: 15000,
    },
    {
      id: "top_7",
      label: "타이다이 티셔츠",
      color: "#888888",
      description: "타이다이 패턴의 티셔츠",
      price: 20000,
    },
    {
      id: "top_8",
      label: "꼬임 티셔츠",
      color: "#888888",
      description: "독특한 꼬임 디자인의 티셔츠",
      price: 76000,
    },
    {
      id: "top_9",
      label: "카라 크롭티",
      color: "#888888",
      description: "카라가 있는 크롭 상의",
      price: 78000,
    },
    {
      id: "top_10",
      label: "셔링 크롭티",
      color: "#888888",
      description: "셔링 주름이 있는 크롭 상의",
      price: 20000,
    },
    {
      id: "top_11",
      label: "잔꽃 나시",
      color: "#888888",
      description: "잔꽃 패턴의 나시 탑",
      price: 20000,
    },
    {
      id: "top_12",
      label: "줄무늬 나시",
      color: "#888888",
      description: "가로 줄무늬 나시",
      price: 10000,
    },
    {
      id: "top_13",
      label: "노랑 반팔셔츠",
      color: "#888888",
      description: "밝은 노란색 반팔 셔츠",
      price: 17000,
    },
    {
      id: "top_14",
      label: "핑크 체크셔츠",
      color: "#888888",
      description: "핑크 톤의 체크 패턴 셔츠",
      price: 15000,
    },
    {
      id: "top_15",
      label: "농장 가디건",
      color: "#888888",
      description: "캐주얼한 농장 테마 가디건",
      price: 110000,
    },
    {
      id: "top_16",
      label: "체크 옴브레 셔츠",
      color: "#888888",
      description: "옴브레 그라데이션 체크 셔츠",
      price: 108000,
    },
    {
      id: "top_17",
      label: "니트 후드",
      color: "#888888",
      description: "부드러운 니트 소재의 후드",
      price: 19000,
    },
    {
      id: "top_18",
      label: "폴라티",
      color: "#888888",
      description: "폴라 소재의 티셔츠",
      price: 19000,
    },
  ],
  bottoms: [
    {
      id: "bottom_1",
      label: "은박지 치마",
      color: "#888888",
      description: "은박지 느낌의 미래지향적 치마",
      price: 140000,
    },
    {
      id: "bottom_2",
      label: "포켓 팬츠",
      color: "#888888",
      description: "다수의 포켓이 있는 팬츠",
      price: 70000,
    },
    {
      id: "bottom_3",
      label: "체크 치마바지",
      color: "#888888",
      description: "체크 패턴의 치마바지",
      price: 27000,
    },
    {
      id: "bottom_4",
      label: "은박지 미니스커트",
      color: "#888888",
      description: "은박지 소재의 미니스커트",
      price: 20000,
    },
    {
      id: "bottom_5",
      label: "카모 스커트",
      color: "#888888",
      description: "군용 카모플라주 패턴 스커트",
      price: 80000,
    },
    {
      id: "bottom_6",
      label: "부츠컷 팬츠",
      color: "#888888",
      description: "부츠컷 실루엣의 팬츠",
      price: 25000,
    },
    {
      id: "bottom_7",
      label: "체크 반바지",
      color: "#888888",
      description: "체크 패턴의 반바지",
      price: 20000,
    },
    {
      id: "bottom_8",
      label: "하트 치마",
      color: "#888888",
      description: "하트 패턴이 있는 치마",
      price: 60000,
    },
    {
      id: "bottom_9",
      label: "카고 머메이드 스커트",
      color: "#888888",
      description: "카고 포켓과 머메이드 실루엣의 조합",
      price: 135000,
    },
  ],
  accessories: [
    {
      id: "acc_1",
      label: "트러커 햇",
      color: "#888888",
      description: "클래식한 트러커 모자",
      price: 130000,
    },
    {
      id: "acc_2",
      label: "저지 크로스백",
      color: "#888888",
      description: "저지 소재의 크로스백",
      price: 87000,
    },
    {
      id: "acc_3",
      label: "데님 베레모",
      color: "#888888",
      description: "데님 소재의 베레모",
      price: 15000,
    },
    {
      id: "acc_4",
      label: "줄무늬 빵모자",
      color: "#888888",
      description: "줄무늬 패턴의 빵모자",
      price: 5000,
    },
    {
      id: "acc_5",
      label: "인도아저씨 가방",
      color: "#888888",
      description: "독특한 디자인의 가방",
      price: 6000,
    },
    {
      id: "acc_6",
      label: "도트 장바구니",
      color: "#888888",
      description: "도트 패턴의 장바구니",
      price: 4500,
    },
  ],
};

window.DRESS_UP_ORDER = ["tops", "bottoms", "accessories"];
